# Generated by Django 4.1.2 on 2022-11-16 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pitapat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="user_key", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nickname",
                    models.CharField(db_column="nickname", max_length=30, unique=True),
                ),
                ("email", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("status", models.CharField(max_length=1)),
                ("gender", models.CharField(max_length=1)),
                ("interested_gender", models.CharField(max_length=1)),
                ("birthday", models.DateTimeField()),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={"verbose_name": "User", "db_table": "E_User", "managed": False,},
            managers=[("objects", pitapat.models.MyUserManager()),],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="chat_key", primary_key=True, serialize=False
                    ),
                ),
                ("valid", models.CharField(max_length=1)),
                ("content", models.TextField()),
                ("reg_dt", models.DateTimeField()),
                ("upd_dt", models.DateTimeField()),
            ],
            options={"db_table": "E_Chat", "managed": False,},
        ),
        migrations.CreateModel(
            name="Chatroom",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="chatroom_key", primary_key=True, serialize=False
                    ),
                ),
                ("user_count", models.IntegerField(db_column="user_count")),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "E_Chatroom", "managed": False,},
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="college_key", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="college_name", max_length=20)),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "College",
                "db_table": "E_College",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Introduction",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="introduction_key", primary_key=True, serialize=False
                    ),
                ),
                ("field", models.TextField()),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Introduction",
                "db_table": "E_Introduction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="major_key", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="major_name", max_length=20)),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
            ],
            options={"verbose_name": "Major", "db_table": "E_Major", "managed": False,},
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="photo_key", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="photo_name", max_length=50)),
                ("path", models.CharField(max_length=256)),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
            ],
            options={"verbose_name": "Photo", "db_table": "E_Photo", "managed": False,},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="tag_key", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="tag_name", max_length=20)),
                ("type", models.CharField(db_column="tag_type", max_length=20)),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
            ],
            options={"verbose_name": "Tag", "db_table": "E_Tag", "managed": False,},
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "key",
                    pitapat.models.UnsignedAutoField(
                        db_column="university_key", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="university_name", max_length=20)),
                ("location", models.CharField(max_length=20)),
                ("email_domain", models.CharField(max_length=20)),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("reg_id", models.CharField(max_length=50)),
                ("upd_dt", models.DateTimeField(auto_now=True)),
                ("upd_id", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "db_table": "E_University",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CollegeMajor",
            fields=[
                (
                    "college",
                    models.OneToOneField(
                        db_column="college_key",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="pitapat.college",
                    ),
                ),
            ],
            options={
                "verbose_name": "College-Major Relationship",
                "db_table": "R_CollegeMajor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pitapat",
            fields=[
                (
                    "from_field",
                    models.OneToOneField(
                        db_column="from",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="pitapat_from",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pitapat",
                "db_table": "R_Pitapat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UniversityCollege",
            fields=[
                (
                    "university",
                    models.OneToOneField(
                        db_column="university_key",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to="pitapat.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "University-College Relationship",
                "db_table": "R_UniversityCollege",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserChatroom",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_key",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Chatroom Relationship",
                "db_table": "R_UserChatRoom",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserTag",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_key",
                        on_delete=django.db.models.deletion.RESTRICT,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Tag Relationship",
                "db_table": "R_UserTag",
                "managed": False,
            },
        ),
    ]
