# Generated by Django 4.1.2 on 2022-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitapat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_key',
            field=models.BigAutoField(db_column='college_key', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='college',
            old_name='college_key',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(db_column='college_name', max_length=20),
        ),
        migrations.RenameField(
            model_name='college',
            old_name='college_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='collegemajor',
            old_name='college_key',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='collegemajor',
            old_name='major_key',
            new_name='major',
        ),
        migrations.AlterField(
            model_name='introduction',
            name='introduction_key',
            field=models.BigAutoField(db_column='introduction_key', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='introduction_key',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='introduction',
            old_name='user_key',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='major',
            name='major_key',
            field=models.BigAutoField(db_column='major_key', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='major',
            old_name='major_key',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(db_column='major_name', max_length=20),
        ),
        migrations.RenameField(
            model_name='major',
            old_name='major_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_key',
            field=models.BigAutoField(db_column='photo_key', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_key',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_name',
            field=models.CharField(db_column='photo_name', max_length=50),
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='photo_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user_key',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_key',
            field=models.BigAutoField(db_column='tag_key', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_key',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(db_column='tag_name', max_length=20),
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(db_column='tag_type', max_length=20),
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tag_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='university',
            name='university_key',
            field=models.BigAutoField(db_column='university_key', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_key',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(db_column='university_name', max_length=20),
        ),
        migrations.RenameField(
            model_name='university',
            old_name='university_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='universitycollege',
            old_name='college_key',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='universitycollege',
            old_name='university_key',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='college_key',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='major_key',
            new_name='major',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='university_key',
            new_name='university',
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='tag_key',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='usertag',
            old_name='user_key',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='collegemajor',
            unique_together={('college', 'major')},
        ),
        migrations.AlterUniqueTogether(
            name='universitycollege',
            unique_together={('university', 'college')},
        ),
        migrations.AlterUniqueTogether(
            name='usertag',
            unique_together={('user', 'tag')},
        ),
    ]
