# Generated by Django 4.1.3 on 2022-11-15 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitapat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="college",
            field=models.ForeignKey(
                db_column="college_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.college",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="major",
            field=models.ForeignKey(
                db_column="major_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.major",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.ForeignKey(
                db_column="university_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.university",
            ),
        ),
    ]
