# Generated by Django 4.1.2 on 2022-11-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitapat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="universitycollege", name="university",),
        migrations.DeleteModel(name="CollegeMajor",),
        migrations.DeleteModel(name="UniversityCollege",),
    ]
