# Generated by Django 4.1.2 on 2022-11-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pitapat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="userchatroom", table="R_UserChatroom",),
    ]
