# Generated by Django 4.1.2 on 2022-11-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitapat', '0002_euser_groups_euser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='euser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
