# Generated by Django 4.1.2 on 2022-11-15 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pitapat", "0002_alter_user_college_alter_user_major_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegemajor",
            name="college",
            field=models.OneToOneField(
                db_column="college_key",
                on_delete=django.db.models.deletion.RESTRICT,
                primary_key=True,
                serialize=False,
                to="pitapat.college",
            ),
        ),
        migrations.AlterField(
            model_name="collegemajor",
            name="major",
            field=models.ForeignKey(
                db_column="major_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.major",
            ),
        ),
        migrations.AlterField(
            model_name="universitycollege",
            name="college",
            field=models.ForeignKey(
                db_column="college_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.college",
            ),
        ),
        migrations.AlterField(
            model_name="universitycollege",
            name="university",
            field=models.OneToOneField(
                db_column="university_key",
                on_delete=django.db.models.deletion.RESTRICT,
                primary_key=True,
                serialize=False,
                to="pitapat.university",
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="tag",
            field=models.ForeignKey(
                db_column="tag_key",
                on_delete=django.db.models.deletion.RESTRICT,
                to="pitapat.tag",
            ),
        ),
        migrations.AlterField(
            model_name="usertag",
            name="user",
            field=models.OneToOneField(
                db_column="user_key",
                on_delete=django.db.models.deletion.RESTRICT,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
