# Generated by Django 4.1.2 on 2022-11-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitapat', '0002_alter_college_college_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_key',
            new_name='key',
        ),
    ]
