# Generated by Django 4.1.2 on 2022-11-15 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitapat', '0003_rename_user_key_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='majors',
            field=models.ManyToManyField(through='pitapat.CollegeMajor', to='pitapat.major'),
        ),
        migrations.AddField(
            model_name='university',
            name='colleges',
            field=models.ManyToManyField(through='pitapat.UniversityCollege', to='pitapat.college'),
        ),
        migrations.AddField(
            model_name='user',
            name='pitapat',
            field=models.ManyToManyField(through='pitapat.Pitapat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(through='pitapat.UserTag', to='pitapat.tag'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(db_column='user_key', on_delete=django.db.models.deletion.DO_NOTHING, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
