# Generated by Django 4.1.2 on 2022-11-15 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitapat', '0004_college_majors_university_colleges_user_pitapat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegemajor',
            name='college',
            field=models.OneToOneField(db_column='college_key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pitapat.college'),
        ),
        migrations.AlterField(
            model_name='collegemajor',
            name='major',
            field=models.ForeignKey(db_column='major_key', on_delete=django.db.models.deletion.CASCADE, to='pitapat.major'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='user',
            field=models.ForeignKey(db_column='user_key', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(db_column='user_key', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pitapat',
            name='from_field',
            field=models.ForeignKey(blank=True, db_column='from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_field', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pitapat',
            name='to',
            field=models.ForeignKey(blank=True, db_column='to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='universitycollege',
            name='college',
            field=models.ForeignKey(db_column='college_key', on_delete=django.db.models.deletion.CASCADE, to='pitapat.college'),
        ),
        migrations.AlterField(
            model_name='universitycollege',
            name='university',
            field=models.OneToOneField(db_column='university_key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pitapat.university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university',
            field=models.ForeignKey(db_column='university_key', on_delete=django.db.models.deletion.CASCADE, to='pitapat.university'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag',
            field=models.ForeignKey(db_column='tag_key', on_delete=django.db.models.deletion.CASCADE, to='pitapat.tag'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.OneToOneField(db_column='user_key', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
