# Generated by Django 4.1.2 on 2022-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitapat', '0005_alter_collegemajor_college_alter_collegemajor_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.BigAutoField(db_column='user_key', primary_key=True, serialize=False),
        ),
    ]
