from .auth import AuthTestCase
from .block import BlockTestCase
from .university import UniversityTestCase
from .chatroom import ChatroomTestCase
from .pitapat import PitapatTestCase
from .user_block import UserBlockTestCase
from .user_chatroom import UserChatroomTestCase
from .user_introduction import UserIntroductionTestCase
from .user_pitapat import UserPitapatTestCase
from .user_photo import UserPhotoTestCase
from .user_tag import UserTagTestCase
from .user import UserTestCase
from .photo import PhotoTestCase
